float posX;
float posY;

size(450,450);
posX = 0;
posY = height/2;

circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
circle(posX,posY,50);
posX = posX + 5;
